server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Live docker ps feed written by the homelab-status sidecar.
    location /status/ {
        alias /usr/share/nginx/status/;
        add_header Cache-Control "no-store";
    }
}
