services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:${HOME_ASSISTANT_VERSION:-stable}
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${HOME_ASSISTANT_CONFIG_PATH:-/opt/homeassistant/config}:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${TZ:-Etc/UTC}
