services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config:ro
      - ./assets:/app/assets:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GLANCE_PORT:-8765}:8080"
