services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    command:
      - --templates
      - https://raw.githubusercontent.com/thatbeautifuldream/homelab/main/portainer/templates/templates-2.0.json
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
